language: php
php:
  - 7.0.20
 
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS databas6;'

before_script:
  - composer install
  - cd application/tests
    
script: ../../vendor/phpunit/phpunit/phpunit --coverage-clover ../../build/logs/clover.xml

after_success:
  - cd ../../
  - ls -l build
  - ls -l build/logs
  - ls -l vendor/phpunit/phpunit
  - ls -l vendor/phpunit/phpunit/build/logs
  - php vendor/bin/php-coveralls -v
