language: php
php:
  - 7.0.20
 
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS databas6;'

before_script:
  - composer install
  - cd application/tests
    
script: ../../vendor/phpunit/phpunit/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
  - php vendor/bin/php-coveralls -v
  - php /vendor/bin/php-coveralls -v
  - php ./vendor/bin/php-coveralls -v
  - php ../../vendor/bin/php-coveralls -v
