language: php
php:
- 7.2.8
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS databas6;'
before_script:
- composer install
- cd application/tests
script: "../../vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml"
after_success:
- cd ../../
- ls -l
- find ../../ -name clover.xml
- ls -l ../../build/logs/
- php vendor/bin/php-coveralls -v --coverage_clover build/logs/clover.xml
deploy:
  provider: heroku
  app: fathomless-meadow-31769
  api_key:
    secure: jJUi5WC2/K5Jh8agcCzKCKMds8I54g1kFbYNljdEoL0oq5Fd+DOgNdQYUJR0Ei2tbkaQS39cxSjeShXhupxnyEeN4wmqa20ne+Et28bzcbtg0XErQkq5Pv7NuErQXryKwONHxh2xAjNQiquFxe5UX5NrpVgmQYB3iPaBa2K/M7PtQ5tJLq9hV3QNqNSw3xxLpT3e9AT9iSZG808lkL0dJ+Oiep7YBEwciuhgmdFARguZ3a8VqRcbSb6bvxdk0k8mwt9yYcbekkEKo6KfOaS1xWYm1PyMg14l9KeEi94H+ZN9RWWmZVTg8cFxpfGDsEYIEb5rI2MFWL5ZTCLzUn9cJWzwGrlRHfWXTwUCb2T6mOhikrI7zzoxcu1xT/BnLiFqtvLPewOErK8BfELMBh66+Lphr8KWDWnrmetW4o4D5/CBbtdgm3+mKYR9qwt1Sy1PyNN/cGAHkplT8Rkprjf+LOyoPjacP2Bntxs47UYIRer02nNLFHRfNFoYVK1BLkObkb0NiFSeozqIdSOrZl0rE+CSoY+FL03/ES831xKDihB1OBzYqVryHlX8h6qCQekWgwprAV7Sg9ZIlwnjZ/hS+ye2jZ2jl42sgpB4XfIwKGhrCfYRinSysaEl3H509mwgLXYFbKtuK2+0XuHYxBHTcwhZxs6TH9W1RvJ8XjcwGMY=
