SELECT * FROM club;

SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE club MODIFY COLUMN id INT auto_increment;

ALTER TABLE club AUTO_INCREMENT = 160;

SET FOREIGN_KEY_CHECKS=1;

DELETE FROM club WHERE id = 1;

SELECT * FROM team;
UPDATE team SET club_id = NULL WHERE id = 170;