DROP TABLE mv_report_03;

CREATE TABLE mv_report_03 (
weekdate DATE DEFAULT NULL,
`No Senior Boundary|BFL` VARCHAR(1000) DEFAULT NULL,
`No Senior Boundary|GDFL` VARCHAR(1000) DEFAULT NULL,
`No Senior Boundary|GFL` VARCHAR(1000) DEFAULT NULL,
`No Senior Boundary|No.` INT(11) DEFAULT NULL,
`No Senior Goal|BFL` VARCHAR(1000) DEFAULT NULL,
`No Senior Goal|GDFL` VARCHAR(1000) DEFAULT NULL,
`No Senior Goal|GFL` VARCHAR(1000) DEFAULT NULL,
`No Senior Goal|No.` INT(11) DEFAULT NULL,
`No Reserve Goal|BFL` VARCHAR(1000) DEFAULT NULL,
`No Reserve Goal|GDFL` VARCHAR(1000) DEFAULT NULL,
`No Reserve Goal|GFL` VARCHAR(1000) DEFAULT NULL,
`No Reserve Goal|No.` INT(11) DEFAULT NULL,
`No Colts Field|Clubs` VARCHAR(1000) DEFAULT NULL,
`No Colts Field|No.` INT(11) DEFAULT NULL,
`No U16 Field|Clubs` VARCHAR(1000) DEFAULT NULL,
`No U16 Field|No.` INT(11) DEFAULT NULL,
`No U14 Field|Clubs` VARCHAR(1000) DEFAULT NULL,
`No U14 Field|No.` INT(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

