drop table if exists mv_report_05;

CREATE TABLE mv_report_05 (
umpire_type VARCHAR(200) DEFAULT NULL,
age_group VARCHAR(200) DEFAULT NULL,
BFL INT(11) DEFAULT NULL,
GDFL INT(11) DEFAULT NULL,
GFL INT(11) DEFAULT NULL,
`None` INT(11) DEFAULT NULL,
`Total` INT(11) DEFAULT NULL

)