DROP TABLE mv_report_04;

CREATE TABLE mv_report_04 (
club_name VARCHAR(200) DEFAULT NULL,
`Boundary|Seniors|BFL` INT(11) DEFAULT NULL,
`Boundary|Seniors|GDFL` INT(11) DEFAULT NULL,
`Boundary|Seniors|GFL` INT(11) DEFAULT NULL,
`Boundary|Reserves|BFL` INT(11) DEFAULT NULL,
`Boundary|Reserves|GDFL` INT(11) DEFAULT NULL,
`Boundary|Reserves|GFL` INT(11) DEFAULT NULL,
`Boundary|Colts|None` INT(11) DEFAULT NULL,
`Boundary|Under 16|None` INT(11) DEFAULT NULL,
`Boundary|Under 14|None` INT(11) DEFAULT NULL,
`Boundary|Youth Girls|None` INT(11) DEFAULT NULL,
`Boundary|Junior Girls|None` INT(11) DEFAULT NULL,
`Field|Seniors|BFL` INT(11) DEFAULT NULL,
`Field|Seniors|GDFL` INT(11) DEFAULT NULL,
`Field|Seniors|GFL` INT(11) DEFAULT NULL,
`Field|Reserves|BFL` INT(11) DEFAULT NULL,
`Field|Reserves|GDFL` INT(11) DEFAULT NULL,
`Field|Reserves|GFL` INT(11) DEFAULT NULL,
`Field|Colts|None` INT(11) DEFAULT NULL,
`Field|Under 16|None` INT(11) DEFAULT NULL,
`Field|Under 14|None` INT(11) DEFAULT NULL,
`Field|Youth Girls|None` INT(11) DEFAULT NULL,
`Field|Junior Girls|None` INT(11) DEFAULT NULL,
`Goal|Seniors|BFL` INT(11) DEFAULT NULL,
`Goal|Seniors|GDFL` INT(11) DEFAULT NULL,
`Goal|Seniors|GFL` INT(11) DEFAULT NULL,
`Goal|Reserves|BFL` INT(11) DEFAULT NULL,
`Goal|Reserves|GDFL` INT(11) DEFAULT NULL,
`Goal|Reserves|GFL` INT(11) DEFAULT NULL,
`Goal|Colts|None` INT(11) DEFAULT NULL,
`Goal|Under 16|None` INT(11) DEFAULT NULL,
`Goal|Under 14|None` INT(11) DEFAULT NULL,
`Goal|Youth Girls|None` INT(11) DEFAULT NULL,
`Goal|Junior Girls|None` INT(11) DEFAULT NULL
)