CREATE TEMPORARY TABLE match_played_all_umpires (
umpire_name_type_id INT(11),
match_id INT(11),
match_staging_id INT(11),
umpire_id INT(11),
field1_first_name VARCHAR(100),
field1_last_name VARCHAR(100),
field2_first_name VARCHAR(100),
field2_last_name VARCHAR(100),
field3_first_name VARCHAR(100),
field3_last_name VARCHAR(100),
boundary1_first_name VARCHAR(100),
boundary1_last_name VARCHAR(100),
boundary2_first_name VARCHAR(100),
boundary2_last_name VARCHAR(100),
boundary3_first_name VARCHAR(100),
boundary3_last_name VARCHAR(100),
boundary4_first_name VARCHAR(100),
boundary4_last_name VARCHAR(100),
boundary5_first_name VARCHAR(100),
boundary5_last_name VARCHAR(100),
boundary6_first_name VARCHAR(100),
boundary6_last_name VARCHAR(100),
goal1_first_name VARCHAR(100),
goal1_last_name VARCHAR(100),
goal2_first_name VARCHAR(100),
goal2_last_name VARCHAR(100),
umpire_type_id INT(11),
umpire_type_name VARCHAR(100)
);

INSERT INTO match_played_all_umpires (
umpire_name_type_id ,
match_id ,
match_staging_id ,
umpire_id ,
field1_first_name ,
field1_last_name ,
field2_first_name ,
field2_last_name ,
field3_first_name ,
field3_last_name ,
boundary1_first_name ,
boundary1_last_name ,
boundary2_first_name ,
boundary2_last_name ,
boundary3_first_name ,
boundary3_last_name ,
boundary4_first_name ,
boundary4_last_name ,
boundary5_first_name ,
boundary5_last_name ,
boundary6_first_name ,
boundary6_last_name ,
goal1_first_name ,
goal1_last_name ,
goal2_first_name ,
goal2_last_name ,
umpire_type_id ,
umpire_type_name
)
SELECT umpire_name_type.ID ,
match_played.ID,
match_staging.match_staging_id,
umpire.id,
match_staging.appointments_field1_first,
match_staging.appointments_field1_last,
match_staging.appointments_field2_first,
match_staging.appointments_field2_last,
match_staging.appointments_field3_first,
match_staging.appointments_field3_last,
match_staging.appointments_boundary1_first,
match_staging.appointments_boundary1_last,
match_staging.appointments_boundary2_first,
match_staging.appointments_boundary2_last,
match_staging.appointments_boundary3_first,
match_staging.appointments_boundary3_last,
match_staging.appointments_boundary4_first,
match_staging.appointments_boundary4_last,
match_staging.appointments_boundary5_first,
match_staging.appointments_boundary5_last,
match_staging.appointments_boundary6_first,
match_staging.appointments_boundary6_last,
match_staging.appointments_goal1_first,
match_staging.appointments_goal1_last,
match_staging.appointments_goal2_first,
match_staging.appointments_goal2_last,
umpire_type.ID,
umpire_type.umpire_type_name
FROM match_played 
INNER JOIN match_staging ON match_staging.match_staging_id = match_played.match_staging_id
INNER JOIN umpire 
	ON (umpire.first_name = match_staging.appointments_field1_first) 
	AND (umpire.last_name = match_staging.appointments_field1_last) 
INNER JOIN umpire_name_type ON umpire.ID = umpire_name_type.umpire_id 
INNER JOIN umpire_type ON umpire_type.ID = umpire_name_type.umpire_type_id 
WHERE umpire_type.umpire_type_name = 'Field';

select * from match_played_all_umpires;
